version: 2
updates:
  - package-ecosystem: docker
    directory: /
    allow:
      - dependency-name: python
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Denver
    open-pull-requests-limit: 1
