#!/usr/bin/env python3
"""Generate the pen-and-ink plates for the home page.

The home page is set like a 1960s motorist's manual. Its drawings are inline
SVG so they take the page's ink and paper colours in both themes; this script
draws them (with seeded randomness for trees, grass, and hatching) and writes
Jinja partials to templates/partials/landing/.

Run from the repository root:

    python scripts/generate_landing_plates.py

Class names map to rules in static/css/landing.css: ``pl-*`` for plate
elements and ``mn-*`` for the Murano.
"""

from __future__ import annotations

import math
import random
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "templates" / "partials" / "landing"
HEADER = (
    "{# Generated by scripts/generate_landing_plates.py. "
    "Edit the generator, not this file. #}\n"
)

DEFS = """<svg class="manual-defs" width="0" height="0" aria-hidden="true" focusable="false">
  <defs>
    <pattern id="manual-hatch" width="3.6" height="3.6" patternUnits="userSpaceOnUse" patternTransform="rotate(58)">
      <line x1="0" y1="0" x2="0" y2="3.6" class="manual-hatch-line"/>
    </pattern>
    <pattern id="manual-hatch-dense" width="2.4" height="2.4" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
      <line x1="0" y1="0" x2="0" y2="2.4" class="manual-hatch-line"/>
    </pattern>
    <filter id="manual-wobble" x="-2%" y="-2%" width="104%" height="104%">
      <feTurbulence type="fractalNoise" baseFrequency="0.035" numOctaves="2" seed="4"/>
      <feDisplacementMap in="SourceGraphic" scale="1.8" xChannelSelector="R" yChannelSelector="G"/>
    </filter>
  </defs>
</svg>"""


# ---------------------------------------------------------------------------
# Drawing helpers
# ---------------------------------------------------------------------------


def n(v):
    s = f"{v:.1f}"
    s = s.rstrip("0").rstrip(".") if "." in s else s
    return "0" if s in ("-0", "") else s


def poly(points, close=True):
    d = "M" + "L".join(f"{n(x)} {n(y)}" for x, y in points)
    return d + ("Z" if close else "")


def smooth(points, close=False, tension=1.0):
    """Catmull-Rom through points -> cubic bezier path."""
    pts = list(points)
    pts = [pts[-1], *pts, pts[0], pts[1]] if close else [pts[0], *pts, pts[-1]]
    d = f"M{n(pts[1][0])} {n(pts[1][1])}"
    for i in range(1, len(pts) - 2):
        p0, p1, p2, p3 = pts[i - 1], pts[i], pts[i + 1], pts[i + 2]
        c1 = (
            p1[0] + (p2[0] - p0[0]) / 6 * tension,
            p1[1] + (p2[1] - p0[1]) / 6 * tension,
        )
        c2 = (
            p2[0] - (p3[0] - p1[0]) / 6 * tension,
            p2[1] - (p3[1] - p1[1]) / 6 * tension,
        )
        d += f"C{n(c1[0])} {n(c1[1])} {n(c2[0])} {n(c2[1])} {n(p2[0])} {n(p2[1])}"
    return d + ("Z" if close else "")


def fir(x, base, h, rnd, spread=0.3, lean=0.0):
    """Jagged conifer silhouette; returns (outline_path, highlight_strokes)."""
    tiers = max(4, int(h / 6.5))
    top = base - h
    trunk_h = max(2.0, h * 0.07)
    crown_bottom = base - trunk_h
    span = crown_bottom - top
    left, right, lights = [], [], []
    for i in range(tiers):
        t = (i + 1) / tiers
        y_tip = top + span * t + rnd.uniform(-0.6, 1.2)
        half = spread * h * (t**0.92) * rnd.uniform(0.82, 1.12)
        notch_y = y_tip - span / tiers * rnd.uniform(0.45, 0.7)
        shift = lean * (1 - t) * h
        cx = x + shift
        left += [(cx - half * rnd.uniform(0.3, 0.45), notch_y), (cx - half, y_tip)]
        right += [
            (cx + half * rnd.uniform(0.3, 0.45), notch_y),
            (cx + half * rnd.uniform(0.86, 1.08), y_tip),
        ]
        if h > 36 and i > 0 and rnd.random() < 0.8:
            lx = cx - half * rnd.uniform(0.35, 0.7)
            lights.append(
                f"M{n(lx)} {n(y_tip - 1.2)}l{n(half * 0.22)} {n(-span / tiers * 0.5)}"
            )
    tw = max(0.9, h * 0.022)
    pts = [
        (x + lean * h, top),
        *right,
        (x + tw, crown_bottom),
        (x + tw, base),
        (x - tw, base),
        (x - tw, crown_bottom),
        *left[::-1],
    ]
    return poly(pts), "".join(lights)


def tuft(x, y, s, rnd):
    d = ""
    k = rnd.randint(3, 6)
    for _i in range(k):
        a = -math.pi / 2 + rnd.uniform(-0.75, 0.75)
        L = s * rnd.uniform(0.5, 1.0)
        ex, ey = (
            x + math.cos(a) * L + rnd.uniform(-0.6, 0.6) * s * 0.2,
            y + math.sin(a) * L,
        )
        mx, my = x + math.cos(a) * L * 0.5 + (ex - x) * 0.15, y + math.sin(a) * L * 0.6
        d += f"M{n(x + rnd.uniform(-1.2, 1.2))} {n(y)}Q{n(mx)} {n(my)} {n(ex)} {n(ey)}"
    return d


# ---------------------------------------------------------------------------
# The 2014 Nissan Murano
# ---------------------------------------------------------------------------

# 2014 Nissan Murano (Z51), side profile facing right. Local box ~200 x 72, ground at y=70.
BODY = (
    "M8 59C4.5 57.5 3 52 3 46C3 39 4.6 33.4 8.2 28.4C11.2 23 15.8 17.6 22.4 13.4"
    "C38 6.4 66 3 92 3C104 3 112 4.5 118 7.5C127 13 134 20 141 27.5"
    "C156 29.5 175 31.5 189 35C195 36.8 198.5 40.5 199 46L199 54.5"
    "C199 57.5 197.5 59.5 194 60L181.5 60"
    "A18.5 18.5 0 0 0 144.5 60L61 60A18.5 18.5 0 0 0 24 60Z"
)
WINDOW_FRONT = (
    "M136.5 28.8C129 21.2 121.5 13.8 115.5 9.6C111 8.2 106 7.6 101 7.4L100.2 28.2Z"
)
WINDOW_REAR = (
    "M96.4 7.3L95.8 28C84 27.6 72 27.2 63.2 26.9L65.2 7.1C76 6.8 87 7 96.4 7.3Z"
)
WINDOW_QUARTER = "M60.8 7.3L58.8 26.6C52.5 24.4 45.5 20.2 39.5 16.6C36 14.6 33 13.6 30.6 13.3C39.5 9.6 50 7.7 60.8 7.3Z"
DETAILS = [
    # hood/cowl, headlamp, grille bars, bumper
    "M182.6 37.6C190.6 37.8 196.6 40.8 198.4 45.8L189.6 45.4C185.2 44.7 181.4 42.2 179.4 38.8Z",
    "M197 47.5H199M196.6 50.2H199M196.8 52.8H199",
    "M188 60C188.8 57 191 55.6 194.5 55.4",
    # tail lamp boomerang
    "M8.6 28.6C11.6 27.4 15.6 27.2 18.4 28.2L13.6 34.6C11.4 38.2 9.6 42 8.6 46.4L4.2 45.6C4.1 39.4 5.6 33.2 8.6 28.6Z",
    # character line and sill
    "M24 39.5C60 42.5 110 44.5 148 43.2",
    "M63 55.2C90 56 118 56 142.5 55.2",
    # door shut lines
    "M137 29.2C139.5 38 141 47 143.2 58.6",
    "M98.6 28.4C98.8 38.4 98.9 48.5 99 59.6",
    "M61.6 27C60 36 59.5 42 61 50",
    # handles
    "M121.5 35.2h7.2M84.5 34.6h7",
    # rear glass edge and spoiler lip
    "M24.8 13.4C19.6 17.4 14.8 22.2 11.8 27.6",
    "M19.6 15.4L28.4 11.6",
    # lower intake, fender flare
    "M184.5 56.8H197.5",
    "M141.5 45.4C146 40.4 151.5 37.8 157 37.2",
]
MIRROR = "M130.5 29.6L137.2 26.2C140.2 25.6 141.8 28 140.2 30.6L133.2 31.6Z"
GLINTS = "M126 25L131.5 16M121 26.5L128 15.5M88 25L93 12M50 22L56 12"


def wheel(cx, cy):
    import math

    r_t, r_r = 14.2, 9.4
    spokes = []
    for i in range(5):
        a = math.radians(-90 + i * 72)
        a1, a2 = a - 0.16, a + 0.16
        spokes.append(
            f"M{cx + 2.4 * math.cos(a1):.2f} {cy + 2.4 * math.sin(a1):.2f}"
            f"L{cx + 8.6 * math.cos(a - 0.2):.2f} {cy + 8.6 * math.sin(a - 0.2):.2f}"
            f"M{cx + 2.4 * math.cos(a2):.2f} {cy + 2.4 * math.sin(a2):.2f}"
            f"L{cx + 8.6 * math.cos(a + 0.2):.2f} {cy + 8.6 * math.sin(a + 0.2):.2f}"
        )
    return (
        f'<circle class="mn-solid" cx="{cx}" cy="{cy}" r="{r_t}"/>'
        f'<circle class="mn-paper mn-line" cx="{cx}" cy="{cy}" r="{r_r}"/>'
        f'<path class="mn-line mn-thin" d="{"".join(spokes)}"/>'
        f'<circle class="mn-line mn-thin" cx="{cx}" cy="{cy}" r="2.2"/>'
        f'<path class="mn-line mn-hair" d="M{cx - 12.2} {cy - 3}A12.6 12.6 0 0 1 {cx + 3} {cy - 12.2}"/>'
    )


def murano():
    parts = [
        '<g class="mn">',
        '<ellipse class="mn-shadow" cx="100" cy="70.5" rx="98" ry="3.6"/>',
        f'<path class="mn-paper mn-line mn-body" d="{BODY}"/>',
        f'<path class="mn-glass" d="{WINDOW_FRONT}"/>',
        f'<path class="mn-glass" d="{WINDOW_REAR}"/>',
        f'<path class="mn-glass" d="{WINDOW_QUARTER}"/>',
        f'<path class="mn-glint" d="{GLINTS}"/>',
        f'<path class="mn-line mn-thin" d="{"".join(DETAILS)}"/>',
        f'<path class="mn-solid" d="{MIRROR}"/>',
        wheel(42.5, 56),
        wheel(163, 56),
        "</g>",
    ]
    return "".join(parts)


# ---------------------------------------------------------------------------
# Plate 1: the hero scene
# ---------------------------------------------------------------------------

W, H = 760, 470


def _range(ridge, base, rnd, caps=(), hatch="pl-hatch", gully=True, fade=0.72):
    out = []
    sil = [*ridge, (ridge[-1][0], base), (ridge[0][0], base)]
    out.append(f'<path class="pl-paper" d="{poly(sil)}"/>')
    shade = []
    peaks = []
    for i in range(1, len(ridge) - 1):
        px, py = ridge[i]
        if py < ridge[i - 1][1] and py < ridge[i + 1][1]:
            peaks.append((px, py))
            j = i + 1
            while j + 1 < len(ridge) and ridge[j + 1][1] > ridge[j][1]:
                j += 1
            vx, vy = ridge[j]
            depth = (base - py) * fade
            low = (px + (vx - px) * rnd.uniform(0.05, 0.2), py + depth)
            mid = (vx - (vx - px) * 0.1, vy + (base - vy) * 0.35)
            shade.append(poly([(px, py), *ridge[i + 1 : j + 1], mid, low]))
    out.append(f'<path class="{hatch}" d="{"".join(shade)}"/>')
    cap_paths = []
    for px, py in peaks:
        if (px, py) not in caps:
            continue
        dep = (base - py) * 0.24
        pts = [(px, py)]
        k = 7
        for s in range(1, k):
            t = s / k
            xx = px - dep * 0.35 + t * dep * 1.3
            yy = (
                py
                + dep * (0.35 + 0.65 * math.sin(t * math.pi))
                + rnd.uniform(-2.5, 2.5)
            )
            pts.append((xx, yy))
        pts.append((px + dep * 0.9, py + dep * 0.55))
        cap_paths.append(poly(pts))
    if cap_paths:
        out.append(f'<path class="pl-paper" d="{"".join(cap_paths)}"/>')
    out.append(f'<path class="pl-line pl-med" d="{poly(ridge, close=False)}"/>')
    if gully:
        g = ""
        for px, py in peaks:
            for _ in range(rnd.randint(2, 4)):
                L = (base - py) * rnd.uniform(0.16, 0.38)
                a = math.radians(rnd.uniform(60, 120))
                sx = px + rnd.uniform(-8, 6)
                sy = py + rnd.uniform(3, 12)
                g += f"M{n(sx)} {n(sy)}q{n(math.cos(a) * L * 0.4)} {n(L * 0.5)} {n(math.cos(a) * L)} {n(L)}"
        out.append(f'<path class="pl-line pl-hair" d="{g}"/>')
    return "".join(out)


def mountains(rnd):
    main = [
        (96, 236),
        (140, 196),
        (166, 204),
        (206, 160),
        (232, 172),
        (272, 124),
        (300, 140),
        (334, 100),
        (356, 112),
        (396, 66),
        (420, 80),
        (462, 30),
        (498, 78),
        (520, 68),
        (552, 100),
        (594, 72),
        (634, 50),
        (672, 92),
        (698, 84),
        (730, 112),
        (764, 104),
    ]
    front = [
        (150, 250),
        (196, 214),
        (222, 222),
        (262, 190),
        (300, 206),
        (344, 170),
        (380, 196),
        (410, 184),
        (446, 212),
        (520, 180),
        (556, 162),
        (596, 196),
        (640, 176),
        (684, 200),
        (726, 170),
        (764, 190),
    ]
    birds = "M540 24q4-4 8 0q4-4 8 0M572 14q3-3 6 0q3-3 6 0M516 40q3-3 6 0q3-3 6 0"
    clouds = "M150 96h58M168 102h72M612 22h66M630 28h40"
    return (
        _range(main, 260, rnd, caps={(462, 30), (634, 50), (396, 66), (594, 72)})
        + _range(
            front, 262, rnd, caps=(), hatch="pl-hatch-dense", gully=False, fade=0.8
        )
        + f'<path class="pl-line pl-thin" d="{birds}"/>'
        + f'<path class="pl-line pl-hair" d="{clouds}"/>'
    )


def far_hills(rnd):
    line = [
        (80, 250),
        (150, 238),
        (230, 244),
        (300, 232),
        (380, 240),
        (430, 236),
        (470, 242),
        (540, 230),
        (620, 238),
        (700, 226),
        (770, 232),
    ]
    out = [
        f'<path class="pl-paper" d="{smooth(line)}L770 300L80 300Z"/>',
        f'<path class="pl-line pl-thin" d="{smooth(line)}"/>',
    ]
    trees = ""
    x = 96
    while x < 760:
        if 418 < x < 492:
            x += 6
            continue
        # height along the hill line
        yb = 236 + 8 * math.sin(x / 37) + rnd.uniform(-2, 4)
        h = rnd.uniform(9, 18) * (1.25 if x < 250 or x > 620 else 1.0)
        p, _ = fir(x, yb + 4, h, rnd, spread=0.28)
        trees += p
        x += rnd.uniform(4.5, 9)
    out.append(f'<path class="pl-tree pl-tree-far" d="{trees}"/>')
    return "".join(out)


def road_edges(center, widths):
    left, right = [], []
    for i, ((x, y), w) in enumerate(zip(center, widths, strict=False)):
        a = center[max(0, i - 1)]
        b = center[min(len(center) - 1, i + 1)]
        dx, dy = b[0] - a[0], b[1] - a[1]
        L = math.hypot(dx, dy) or 1
        nx, ny = -dy / L, dx / L
        left.append((x + nx * w / 2, y + ny * w / 2))
        right.append((x - nx * w / 2, y - ny * w / 2))
    return left, right


def sample_path(pts, steps=10):
    """Densify a Catmull-Rom curve for edge offsetting."""
    P = [pts[0], *pts, pts[-1]]
    out = []
    for i in range(1, len(P) - 2):
        p0, p1, p2, p3 = P[i - 1], P[i], P[i + 1], P[i + 2]
        for s in range(steps):
            t = s / steps
            t2, t3 = t * t, t * t * t
            x = 0.5 * (
                (2 * p1[0])
                + (-p0[0] + p2[0]) * t
                + (2 * p0[0] - 5 * p1[0] + 4 * p2[0] - p3[0]) * t2
                + (-p0[0] + 3 * p1[0] - 3 * p2[0] + p3[0]) * t3
            )
            y = 0.5 * (
                (2 * p1[1])
                + (-p0[1] + p2[1]) * t
                + (2 * p0[1] - 5 * p1[1] + 4 * p2[1] - p3[1]) * t2
                + (-p0[1] + 3 * p1[1] - 3 * p2[1] + p3[1]) * t3
            )
            out.append((x, y))
    out.append(pts[-1])
    return out


def road(rnd):
    # foreground crossing, then a bend away and switchbacks into the notch in the hills
    center = [
        (-20, 408),
        (120, 402),
        (260, 392),
        (380, 378),
        (452, 360),
        (478, 336),
        (462, 314),
        (420, 298),
        (396, 284),
        (408, 270),
        (440, 261),
        (452, 252),
        (446, 245),
        (452, 240),
    ]
    pts = sample_path(center, 12)
    horizon = 236
    widths = [max(2.2, min(62, (y - horizon) * 0.37)) for (x, y) in pts]
    left, right = road_edges(pts, widths)
    surface = poly(left + right[::-1])
    out = [f'<path class="pl-road" d="{surface}"/>']
    out.append(f'<path class="pl-line pl-med" d="{poly(left, close=False)}"/>')
    out.append(f'<path class="pl-line pl-med" d="{poly(right, close=False)}"/>')
    # centre dashes, spaced by perspective
    dashes = ""
    acc = 0.0
    for i in range(1, len(pts)):
        (x0, y0), (x1, y1) = pts[i - 1], pts[i]
        seg = math.hypot(x1 - x0, y1 - y0)
        w = widths[i]
        period = max(3.0, w * 0.5)
        acc += seg
        if acc > period and w > 5:
            acc = 0
            dx, dy = (x1 - x0) / (seg or 1), (y1 - y0) / (seg or 1)
            L = period * 0.5
            dashes += f"M{n(x1)} {n(y1)}l{n(dx * L)} {n(dy * L)}"
    out.append(f'<path class="pl-dash" d="{dashes}"/>')
    # shoulder texture on the near edge
    tex = ""
    for i in range(0, len(right), 3):
        x, y = right[i]
        w = widths[i]
        if w > 20:
            tex += f"M{n(x + rnd.uniform(-2, 2))} {n(y - 2)}l{n(rnd.uniform(6, 14))} {n(rnd.uniform(-0.5, 0.5))}"
    out.append(f'<path class="pl-line pl-hair" d="{tex}"/>')
    return "".join(out), pts, widths


def meadow(rnd):
    out = []
    # mid ground band between hills and road, with scattered tufts
    tufts = ""
    for x, y in (
        (236, 300),
        (262, 286),
        (318, 296),
        (352, 312),
        (500, 298),
        (512, 276),
        (286, 318),
    ):
        for _ in range(rnd.randint(1, 3)):
            tufts += tuft(
                x + rnd.uniform(-8, 8), y + rnd.uniform(-3, 3), rnd.uniform(3, 5), rnd
            )
    for _ in range(34):
        x = rnd.uniform(-10, 420)
        y = 360 - x * 0.07 + rnd.uniform(-4, 4)
        tufts += tuft(x, y, rnd.uniform(4, 8), rnd)
    for _ in range(46):
        x = rnd.uniform(0, 470)
        y = rnd.uniform(430, 466)
        tufts += tuft(x, y, rnd.uniform(6, 12), rnd)
    out.append(f'<path class="pl-line pl-hair" d="{tufts}"/>')
    return "".join(out)


def tree_clusters(rnd):
    out = []
    specs = []
    # left stand behind the car
    for x, h in [
        (28, 118),
        (52, 150),
        (78, 104),
        (104, 132),
        (132, 92),
        (156, 70),
        (178, 56),
        (12, 84),
        (200, 44),
    ]:
        specs.append(
            (
                x + rnd.uniform(-4, 4),
                372 + rnd.uniform(-6, 2),
                h * rnd.uniform(0.92, 1.05),
            )
        )
    # right stand by the bend
    for x, h in [
        (534, 112),
        (560, 86),
        (584, 128),
        (612, 98),
        (640, 76),
        (666, 104),
        (694, 70),
        (720, 88),
        (742, 62),
    ]:
        specs.append(
            (
                x + rnd.uniform(-4, 4),
                330 + rnd.uniform(-5, 3),
                h * rnd.uniform(0.9, 1.05),
            )
        )
    specs.sort(key=lambda s: s[1] - s[2] * 0.01)
    trees, lights = "", ""
    for x, b, h in specs:
        p, light = fir(x, b, h, rnd, spread=0.27, lean=rnd.uniform(-0.02, 0.02))
        trees += p
        lights += light
    out.append(f'<path class="pl-tree" d="{trees}"/>')
    out.append(f'<path class="pl-light" d="{lights}"/>')
    return "".join(out)


def sign():
    # distance sign on two posts, right of the bend
    x, y, w, h = 538, 176, 150, 58
    return (
        '<g class="pl-sign">'
        f'<path class="pl-line pl-med" d="M{x + 26} {y + h}V{y + h + 86}M{x + w - 26} {y + h}V{y + h + 86}"/>'
        f'<path class="pl-line pl-hair" d="M{x + 24} {y + h + 84}h5M{x + w - 28} {y + h + 84}h5"/>'
        f'<rect class="pl-sign-board" x="{x}" y="{y}" width="{w}" height="{h}" rx="5"/>'
        f'<rect class="pl-line pl-thin" x="{x + 4}" y="{y + 4}" width="{w - 8}" height="{h - 8}" rx="3"/>'
        f'<text class="pl-sign-name" id="hero-sign-name" x="{x + w / 2}" y="{y + 26}" text-anchor="middle">EVERY STREET</text>'
        f'<text class="pl-sign-miles" id="hero-sign-miles" x="{x + w / 2}" y="{y + 46}" text-anchor="middle"></text>'
        "</g>"
    )


def folded_map(rnd):
    # accordion-folded road map lying in the foreground, slightly rotated
    g = ['<g class="pl-map" transform="translate(470 352) rotate(-7)">']
    panels = 4
    pw, ph = 66, 104
    xs = [i * pw for i in range(panels + 1)]
    lift = [0, -7, 0, -7, 0]
    # panel faces
    for i in range(panels):
        a = (xs[i], lift[i])
        b = (xs[i + 1], lift[i + 1])
        c = (xs[i + 1], ph + lift[i + 1] * 0.4)
        d = (xs[i], ph + lift[i] * 0.4)
        cls = "pl-map-face" if i % 2 == 0 else "pl-map-face pl-map-face-shade"
        g.append(f'<path class="{cls}" d="{poly([a, b, c, d])}"/>')
    # street grid, clipped per panel by simple bounds
    grid = ""
    for i in range(panels):
        x0 = xs[i]
        for k in range(1, 6):
            yy = 12 + k * 15 + rnd.uniform(-2, 2)
            grid += f"M{n(x0 + 3)} {n(yy + lift[i] * (1 - k / 6))}L{n(x0 + pw - 3)} {n(yy + rnd.uniform(-3, 3) + lift[i + 1] * (1 - k / 6))}"
        for k in range(1, 4):
            xx = x0 + k * pw / 4 + rnd.uniform(-3, 3)
            grid += f"M{n(xx)} {n(8 + (lift[i] + lift[i + 1]) / 2)}L{n(xx + rnd.uniform(-4, 4))} {n(ph - 6)}"
    g.append(f'<path class="pl-line pl-hair" d="{grid}"/>')
    # river
    g.append(
        f'<path class="pl-water" d="{smooth([(0, 70), (40, 62), (80, 78), (130, 66), (190, 84), (264, 72)])}"/>'
    )
    # highway
    g.append(
        f'<path class="pl-hwy" d="{smooth([(0, 30), (60, 38), (120, 24), (190, 34), (264, 22)])}"/>'
    )
    # the route, pencilled in rust
    g.append(
        f'<path class="pl-route" d="{smooth([(22, 94), (40, 76), (70, 60), (104, 54), (140, 40), (176, 50), (206, 30)])}"/>'
    )
    g.append('<path class="pl-route-end" d="M202 26l8 8M210 26l-8 8"/>')
    g.append('<circle class="pl-route-start" cx="22" cy="94" r="3"/>')
    # fold creases
    creases = "".join(
        f"M{xs[i]} {lift[i]}L{xs[i]} {ph + lift[i] * 0.4}" for i in range(1, panels)
    )
    g.append(f'<path class="pl-line pl-thin" d="{creases}"/>')
    # cartouche
    g.append('<rect class="pl-map-cartouche" x="68" y="64" width="112" height="26"/>')
    g.append('<rect class="pl-line pl-hair" x="71" y="67" width="106" height="20"/>')
    g.append(
        '<text class="pl-map-title" id="hero-map-title" x="124" y="81.5" text-anchor="middle">Road Map</text>'
    )
    g.append("</g>")
    return "".join(g)


def compass():
    cx, cy, r = 714, 432, 32
    ticks = ""
    for d in range(0, 360, 10):
        a = math.radians(d)
        r1 = r - (5 if d % 90 == 0 else 3)
        ticks += f"M{n(cx + math.cos(a) * r1)} {n(cy + math.sin(a) * r1)}L{n(cx + math.cos(a) * (r - 1))} {n(cy + math.sin(a) * (r - 1))}"
    star = []
    for k in range(8):
        a = math.radians(k * 45 - 90)
        L = 22 if k % 2 == 0 else 12
        a1, a2 = a - math.radians(22.5), a + math.radians(22.5)
        tip = (cx + math.cos(a) * L, cy + math.sin(a) * L)
        s1 = (cx + math.cos(a1) * 4.2, cy + math.sin(a1) * 4.2)
        s2 = (cx + math.cos(a2) * 4.2, cy + math.sin(a2) * 4.2)
        star.append((tip, s1, s2, k % 2 == 0))
    rose = ""
    rose_dark = ""
    for tip, s1, s2, _major in star:
        rose += poly([(cx, cy), s1, tip, s2])
        rose_dark += poly([(cx, cy), s1, tip])
    return (
        '<g class="pl-compass">'
        f'<ellipse class="pl-shadow" cx="{cx + 5}" cy="{cy + 8}" rx="{r + 2}" ry="{r - 6}"/>'
        f'<path class="pl-line pl-med pl-paper" d="M{cx - 5} {cy - r - 1}v-6a5 5 0 0 1 10 0v6"/>'
        f'<circle class="pl-line pl-body pl-paper" cx="{cx}" cy="{cy}" r="{r + 3}"/>'
        f'<circle class="pl-line pl-thin" cx="{cx}" cy="{cy}" r="{r}"/>'
        f'<path class="pl-line pl-hair" d="{ticks}"/>'
        f'<path class="pl-line pl-thin pl-paper" d="{rose}"/>'
        f'<path class="pl-solid" d="{rose_dark}"/>'
        f'<path class="pl-needle" d="M{cx} {cy - 25}L{cx + 3.2} {cy}L{cx - 3.2} {cy}Z"/>'
        f'<circle class="pl-line pl-thin pl-paper" cx="{cx}" cy="{cy}" r="2.4"/>'
        f'<text class="pl-compass-n" x="{cx}" y="{cy - r + 13}" text-anchor="middle">N</text>'
        "</g>"
    )


def hero():
    rnd = random.Random(11)
    parts = [
        f'<svg class="plate plate-hero" viewBox="0 0 {W} {H}" role="img" aria-labelledby="hero-plate-title">',
        '<title id="hero-plate-title">Pen-and-ink drawing of a 2014 Nissan Murano on a mountain road, with a road sign, a folded map, and a compass.</title>',
        '<g class="plate-ink">',
        mountains(rnd),
        far_hills(rnd),
    ]
    road_svg, _pts, _widths = road(rnd)
    parts.append(meadow(rnd))
    parts.append(tree_clusters(rnd))
    parts.append(sign())
    parts.append(road_svg)
    # the car, climbing gently along the crossing
    parts.append(
        '<g transform="translate(92 318) rotate(-2.4) scale(1.3)">' + murano() + "</g>"
    )
    parts.append(folded_map(rnd))
    parts.append(compass())
    parts.append("</g></svg>")
    return "".join(parts)


# ---------------------------------------------------------------------------
# Action plates and margin vignettes
# ---------------------------------------------------------------------------


def plate_map():
    """An opened accordion road map with a route and a position pin."""
    rnd = random.Random(5)
    # three panels in loose perspective: top edge rises to the right
    P = [(18, 56), (84, 34), (150, 48), (214, 22)]
    B = [(34, 150), (98, 132), (160, 146), (222, 120)]
    out = ['<g class="plate-ink">']
    out.append(
        f'<path class="pl-shadow" d="{poly([(30, 154), (100, 138), (164, 152), (228, 126), (232, 130), (166, 158), (100, 144), (32, 160)])}"/>'
    )
    for i in range(3):
        cls = "pl-map-face" if i != 1 else "pl-map-face pl-map-face-shade"
        out.append(
            f'<path class="{cls}" d="{poly([P[i], P[i + 1], B[i + 1], B[i]])}"/>'
        )

    def lerp(a, b, t):
        return (a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t)

    def at(u, v):
        """u in 0..3 across panels, v in 0..1 down."""
        i = min(2, int(u))
        t = u - i
        top = lerp(P[i], P[i + 1], t)
        bot = lerp(B[i], B[i + 1], t)
        return lerp(top, bot, v)

    grid = ""
    for k in range(1, 9):
        v = k / 9
        pts = [at(u / 6, v) for u in range(19)]
        grid += poly(pts, close=False)
    for k in range(1, 12):
        u = k / 4
        grid += poly([at(u, 0.04), at(u + rnd.uniform(-0.05, 0.05), 0.96)], close=False)
    out.append(f'<path class="pl-line pl-hair" d="{grid}"/>')
    # a park block and a lake
    out.append(
        f'<path class="pl-hatch-dense" d="{poly([at(0.5, 0.56), at(0.75, 0.56), at(0.75, 0.78), at(0.5, 0.78)])}"/>'
    )
    out.append(
        f'<path class="pl-water-fill" d="{smooth([at(2.2, 0.62), at(2.55, 0.55), at(2.75, 0.7), at(2.5, 0.84), at(2.2, 0.62)])}"/>'
    )
    # river and highway
    out.append(
        f'<path class="pl-water" d="{smooth([at(0, 0.3), at(0.6, 0.38), at(1.2, 0.26), at(1.9, 0.4), at(2.99, 0.3)])}"/>'
    )
    out.append(
        f'<path class="pl-hwy" d="{smooth([at(0.02, 0.9), at(0.9, 0.7), at(1.6, 0.74), at(2.3, 0.46), at(2.98, 0.16)])}"/>'
    )
    # route
    out.append(
        f'<path class="pl-route pl-route-solid" d="{smooth([at(0.25, 0.2), at(0.6, 0.45), at(1.1, 0.5), at(1.45, 0.62), at(1.9, 0.58), at(2.2, 0.32)])}"/>'
    )
    # creases
    out.append(
        f'<path class="pl-line pl-thin" d="M{n(P[1][0])} {n(P[1][1])}L{n(B[1][0])} {n(B[1][1])}M{n(P[2][0])} {n(P[2][1])}L{n(B[2][0])} {n(B[2][1])}"/>'
    )
    # position pin
    px, py = at(2.2, 0.32)
    out.append(
        f'<path class="pl-pin" d="M{n(px)} {n(py)}c-2-6-8-10-8-16a8 8 0 0 1 16 0c0 6-6 10-8 16Z"/>'
        f'<circle class="pl-paper pl-line pl-thin" cx="{n(px)}" cy="{n(py - 16)}" r="3.2"/>'
    )
    out.append("</g>")
    return f'<svg class="plate plate-action" viewBox="0 0 240 170" aria-hidden="true" focusable="false">{"".join(out)}</svg>'


def plate_pencil():
    """A pencil tracing an undriven route across a street grid."""
    rnd = random.Random(8)
    out = ['<g class="plate-ink">']
    # street grid sketched loosely; undriven streets dashed
    grid, undriven = "", ""
    xs = [20, 58, 96, 134, 172, 210]
    ys = [26, 58, 90, 122, 150]
    for y in ys:
        for j in range(len(xs) - 1):
            seg = f"M{xs[j]} {y + rnd.uniform(-1, 1):.1f}L{xs[j + 1]} {y + rnd.uniform(-1, 1):.1f}"
            if rnd.random() < 0.38:
                undriven += seg
            else:
                grid += seg
    for x in xs:
        for i in range(len(ys) - 1):
            seg = f"M{x + rnd.uniform(-1, 1):.1f} {ys[i]}L{x + rnd.uniform(-1, 1):.1f} {ys[i + 1]}"
            if rnd.random() < 0.38:
                undriven += seg
            else:
                grid += seg
    out.append(f'<path class="pl-line pl-thin" d="{grid}"/>')
    out.append(f'<path class="pl-line pl-thin pl-undriven" d="{undriven}"/>')
    # a block of hatching (a park) and a diagonal avenue
    out.append('<path class="pl-hatch-dense" d="M100 94h30v24h-30Z"/>')
    out.append('<path class="pl-line pl-med" d="M14 150C60 128 104 70 216 20"/>')
    # traced route in rust ending at the pencil tip
    route = "M20 150L58 150L58 122L96 122L96 90L134 90"
    out.append(f'<path class="pl-route pl-route-solid" d="{route}"/>')
    out.append('<circle class="pl-route-start" cx="20" cy="150" r="3.2"/>')
    # pencil, tip at (152, 58), body running up and to the right
    ang = math.radians(-33)
    ux, uy = math.cos(ang), math.sin(ang)
    vx, vy = -uy, ux
    tip = (134, 90)

    def pt(a, b):
        return (tip[0] + ux * a + vx * b, tip[1] + uy * a + vy * b)

    w = 5.2
    lead = [tip, pt(8, -1.6), pt(8, 1.6)]
    cone = [tip, pt(20, -w), pt(20, w)]
    body = [pt(20, -w), pt(88, -w), pt(88, w), pt(20, w)]
    ferrule = [pt(88, -w - 0.4), pt(100, -w - 0.4), pt(100, w + 0.4), pt(88, w + 0.4)]
    eraser = [
        pt(100, -w + 0.2),
        pt(110, -w + 0.2),
        pt(112, -w + 2),
        pt(112, w - 2),
        pt(110, w - 0.2),
        pt(100, w - 0.2),
    ]

    def sh(a, b):
        x, y = pt(a, b)
        return (x + 3, y + 7)

    out.append(
        f'<path class="pl-shadow" d="{poly([sh(4, 0), sh(112, -w + 1), sh(112, w - 1)])}"/>'
    )
    out.append(f'<path class="pl-wood pl-line pl-thin" d="{poly(cone)}"/>')
    out.append(f'<path class="pl-solid" d="{poly(lead)}"/>')
    out.append(f'<path class="pl-pencil pl-line pl-thin" d="{poly(body)}"/>')
    facets = poly([pt(22, -1.7), pt(88, -1.7)], close=False) + poly(
        [pt(22, 1.7), pt(88, 1.7)], close=False
    )
    out.append(f'<path class="pl-line pl-hair" d="{facets}"/>')
    # scalloped cone edge
    scal = "".join(
        f"M{n(pt(20, s)[0])} {n(pt(20, s)[1])}Q{n(pt(17.5, s + 1.3)[0])} {n(pt(17.5, s + 1.3)[1])} {n(pt(20, s + 2.6)[0])} {n(pt(20, s + 2.6)[1])}"
        for s in (-5.2, -2.6, 0, 2.6)
    )
    out.append(f'<path class="pl-line pl-hair" d="{scal}"/>')
    out.append(f'<path class="pl-ferrule pl-line pl-thin" d="{poly(ferrule)}"/>')
    ribs = "".join(
        poly([pt(a, -w - 0.4), pt(a, w + 0.4)], close=False) for a in (91, 94, 97)
    )
    out.append(f'<path class="pl-line pl-hair" d="{ribs}"/>')
    out.append(f'<path class="pl-eraser pl-line pl-thin" d="{poly(eraser)}"/>')
    out.append("</g>")
    return f'<svg class="plate plate-action" viewBox="0 0 240 170" aria-hidden="true" focusable="false">{"".join(out)}</svg>'


def vignette_transit():
    """A surveyor's transit on a wooden tripod, with a plumb bob and a flagged stake."""
    rnd = random.Random(3)
    o = ['<g class="plate-ink">']
    # legs
    legs = [
        ((56, 94), (62, 94), (20, 186), (14, 186)),
        ((58, 96), (62, 96), (63, 192), (57, 192)),
        ((58, 94), (64, 94), (108, 186), (102, 186)),
    ]
    for a, b, c, d in legs:
        o.append(f'<path class="pl-wood pl-line pl-thin" d="{poly([a, b, c, d])}"/>')
    o.append(
        '<path class="pl-line pl-thin" d="M14 186l-3 6M20 186l-2 6M57 192v6M63 192v6M102 186l3 6M108 186l2 6"/>'
    )
    o.append('<path class="pl-line pl-hair" d="M27 160l8 3M52 160h12M88 163l8-3"/>')
    # plumb line and bob
    o.append('<path class="pl-line pl-hair" d="M60 100V160"/>')
    o.append('<path class="pl-solid" d="M57 160h6l-3 9Z"/>')
    # head plate and leveling base
    o.append(
        '<ellipse class="pl-paper pl-line pl-thin" cx="60" cy="94" rx="20" ry="4.5"/>'
    )
    o.append('<path class="pl-paper pl-line pl-thin" d="M46 82h28l4 10H42Z"/>')
    o.append('<path class="pl-line pl-hair" d="M48 86v5M60 86v6M72 86v5"/>')
    o.append(
        '<ellipse class="pl-paper pl-line pl-thin" cx="60" cy="80" rx="19" ry="4"/>'
    )
    # standards
    o.append(
        '<path class="pl-paper pl-line pl-thin" d="M44 78L48 50H55L56 78ZM64 78L65 50H72L76 78Z"/>'
    )
    # telescope
    o.append('<path class="pl-paper pl-line pl-med" d="M30 44H90V56H30Z"/>')
    o.append('<path class="pl-paper pl-line pl-med" d="M88 41H100V59H88Z"/>')
    o.append('<path class="pl-solid" d="M20 46H30V54H20Z"/>')
    o.append('<path class="pl-line pl-hair" d="M36 44V56M84 44V56M92 41V59"/>')
    # vertical circle
    ticks = "".join(
        f"M{n(60 + math.cos(math.radians(d)) * 9)} {n(50 + math.sin(math.radians(d)) * 9)}L{n(60 + math.cos(math.radians(d)) * 11)} {n(50 + math.sin(math.radians(d)) * 11)}"
        for d in range(0, 360, 20)
    )
    o.append('<circle class="pl-paper pl-line pl-thin" cx="60" cy="50" r="12"/>')
    o.append(f'<path class="pl-line pl-hair" d="{ticks}"/>')
    o.append('<circle class="pl-solid" cx="60" cy="50" r="2.4"/>')
    # level vial
    o.append(
        '<path class="pl-paper pl-line pl-thin" d="M44 36H76A3 3 0 0 1 76 42H44A3 3 0 0 1 44 36Z"/>'
    )
    o.append(
        '<path class="pl-bubble" d="M58 37.4H63A1.6 1.6 0 0 1 63 40.6H58A1.6 1.6 0 0 1 58 37.4Z"/>'
    )
    # stake with flagging
    o.append('<path class="pl-wood pl-line pl-thin" d="M112 146h5v48h-5Z"/>')
    o.append('<path class="pl-flag" d="M117 150c7 2 10 7 16 6c-5 3-9 8-16 4Z"/>')
    tufts = "".join(
        tuft(x, 196, rnd.uniform(5, 9), rnd) for x in (6, 30, 48, 76, 94, 124, 132)
    )
    o.append(f'<path class="pl-line pl-hair" d="{tufts}"/>')
    o.append("</g>")
    return f'<svg class="plate plate-vignette" viewBox="0 0 140 200" aria-hidden="true" focusable="false">{"".join(o)}</svg>'


def vignette_pump():
    """A 1960s service-station gas pump."""
    random.Random(2)
    o = ['<g class="plate-ink">']
    o.append('<ellipse class="pl-shadow" cx="58" cy="192" rx="52" ry="5"/>')
    # plinth and body
    o.append('<path class="pl-paper pl-line pl-med" d="M14 180H102V192H14Z"/>')
    o.append(
        '<path class="pl-paper pl-line pl-body" d="M22 180V44Q22 30 36 30H80Q94 30 94 44V180Z"/>'
    )
    # crown panel with a star emblem
    o.append('<path class="pl-solid" d="M28 38H88V64H28Z"/>')
    star = []
    for k in range(10):
        r = 9 if k % 2 == 0 else 3.8
        a = math.radians(-90 + k * 36)
        star.append((58 + math.cos(a) * r, 51 + math.sin(a) * r))
    o.append(f'<path class="pl-star" d="{poly(star)}"/>')
    # dial face
    o.append('<path class="pl-paper pl-line pl-med" d="M30 72H86V116H30Z"/>')
    o.append('<path class="pl-line pl-hair" d="M30 94H86"/>')
    for _row, y in ((0, 76), (1, 98)):
        for k in range(4):
            x = 44 + k * 9
            o.append(
                f'<rect class="pl-solid" x="{x}" y="{y + 2}" width="7" height="11"/>'
            )
    o.append(
        '<text class="pl-pump-label" x="34" y="84.5">$</text><text class="pl-pump-label" x="34" y="106.5">G</text>'
    )
    for y in (87.8, 109.8):
        for k, d in enumerate("0127"):
            o.append(
                f'<text class="pl-pump-digits" x="{47.5 + k * 9}" y="{y}" text-anchor="middle">{d}</text>'
            )
    # lower louvers
    louvers = "".join(f"M32 {y}H84" for y in range(128, 174, 6))
    o.append(f'<path class="pl-line pl-thin" d="{louvers}"/>')
    o.append('<path class="pl-line pl-thin" d="M30 122H86V176H30Z"/>')
    # nozzle holster, hose, nozzle
    o.append('<path class="pl-paper pl-line pl-thin" d="M94 74H104V96H94Z"/>')
    o.append(
        '<path class="pl-line pl-body" d="M96 150C118 150 124 128 118 110C114 100 110 98 106 96"/>'
    )
    o.append('<path class="pl-solid" d="M100 74L108 70L112 74L106 86L100 84Z"/>')
    o.append('<path class="pl-line pl-med" d="M108 71L116 60"/>')
    # a pair of shading hatches down the right side of the cabinet
    o.append('<path class="pl-hatch" d="M88 122H94V180H88Z"/>')
    o.append("</g>")
    return f'<svg class="plate plate-vignette" viewBox="0 0 130 200" aria-hidden="true" focusable="false">{"".join(o)}</svg>'


def vignette_pines():
    """A small stand of pines under a far ridge, for the logbook margin."""
    rnd = random.Random(21)
    o = ['<g class="plate-ink">']
    ridge = [
        (0, 70),
        (30, 46),
        (46, 54),
        (76, 22),
        (100, 44),
        (122, 36),
        (150, 58),
        (180, 44),
        (210, 62),
    ]
    o.append(f'<path class="pl-paper" d="{poly([*ridge, (210, 110), (0, 110)])}"/>')
    shade = (
        poly([(76, 22), (100, 44), (96, 70), (82, 60)])
        + poly([(30, 46), (46, 54), (44, 72), (34, 64)])
        + poly([(122, 36), (150, 58), (144, 76), (128, 60)])
    )
    o.append(f'<path class="pl-hatch" d="{shade}"/>')
    o.append(f'<path class="pl-line pl-med" d="{poly(ridge, close=False)}"/>')
    o.append(
        f'<path class="pl-paper" d="{smooth([(0, 104), (60, 92), (120, 98), (210, 88)])}L210 140L0 140Z"/>'
    )
    o.append(
        f'<path class="pl-line pl-thin" d="{smooth([(0, 104), (60, 92), (120, 98), (210, 88)])}"/>'
    )
    trees, lights = "", ""
    for x, b, h in [
        (40, 118, 70),
        (64, 124, 92),
        (88, 120, 62),
        (112, 126, 50),
        (22, 122, 44),
        (150, 116, 40),
        (170, 118, 30),
        (132, 122, 34),
    ]:
        p, light = fir(x, b, h, rnd, spread=0.27)
        trees += p
        lights += light
    o.append(f'<path class="pl-tree" d="{trees}"/>')
    o.append(f'<path class="pl-light" d="{lights}"/>')
    tufts = "".join(
        tuft(x, 130 + rnd.uniform(-3, 3), rnd.uniform(5, 9), rnd)
        for x in range(4, 206, 14)
    )
    o.append(f'<path class="pl-line pl-hair" d="{tufts}"/>')
    o.append("</g>")
    return f'<svg class="plate plate-vignette" viewBox="0 0 210 140" aria-hidden="true" focusable="false">{"".join(o)}</svg>'


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------


def pretty(svg: str) -> str:
    return re.sub(r">\s*<", ">\n<", svg).strip() + "\n"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    files = {
        "_plate_defs.html": DEFS,
        "_plate_hero.html": hero(),
        "_plate_map.html": plate_map(),
        "_plate_pencil.html": plate_pencil(),
        "_vignette_transit.html": vignette_transit(),
        "_vignette_pump.html": vignette_pump(),
        "_vignette_pines.html": vignette_pines(),
    }
    for name, svg in files.items():
        (OUT / name).write_text(HEADER + pretty(svg), encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT) / name}")


if __name__ == "__main__":
    main()
